spring:
  profiles:
    active: production or development 

  mail:
    host: host@email.com
    port: XXX
    username: yourmail@email.com
    password: XXXX XXXX XXXX XXXX
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enable: true

  data:
    mongodb:
      uri: mongodb uri
      database: DB Name
      auto-index-creation: true
    redis:
      host: redis.host
      port: XXXX
      password: XXXXXXXXXXXXXXXXXXXXXXXXXXX

  kafka:
    bootstrap-servers: your-confluent-bootstrap-server:9092

    client-id: journaling-app-kafka-client

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: journaling-app-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.nilesh.JournalingApp.Entity

    properties:
      security:
        protocol: SASL_SSL

      sasl:
        mechanism: PLAIN
        jaas:
          config: >-
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username='YOUR_KAFKA_API_KEY'
            password='YOUR_KAFKA_API_SECRET';

      session:
        timeout:
          ms: 45000

weather:
  api:
    key: Weather API key

