spring:
  profiles:
    active: production

  mail:
    host: smtp.gmail.com
    port: 587
    username: yourmail@gmail.com
    password: XXXX XXXX XXXX XXXX

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      uri: mongodb://your-mongodb-uri
      database: your-database-name
      auto-index-creation: true

    redis:
      host: your-redis-host
      port: XXXX
      password: XXXXXXXXXXXXXXXXXXXXXXXXXXX

  kafka:
    bootstrap-servers: your-confluent-bootstrap-server:9092

    client-id: journaling-app-kafka-client

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: journaling-app-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring:
          json:
            trusted:
              packages: com.nilesh.JournalingApp.Entity

    properties:
      security:
        protocol: SASL_SSL

      sasl:
        mechanism: PLAIN
        jaas:
          config: >-
            org.apache.kafka.common.security.plain.PlainLoginModule required
            username='YOUR_KAFKA_API_KEY'
            password='YOUR_KAFKA_API_SECRET';

      session:
        timeout:
          ms: 45000

weather:
  api:
    key: YOUR_WEATHER_API_KEY

SECRET_KEY: YOUR_SECRET_KEY_OF_JWTUtil